server:
  port: 8080

ribbon:
  eureka:
    enabled: false

notify:
  ribbon:
    listOfServers: http://localhost:5000

spring:
  application:
    name: datacenter
  data:
    mongodb:
      database: datacenter
      host: localhost
      port: 27017
